language: python

python:
  - "3.8"
  # TODO: Add more and windows OS as well.

cache: pip

install:
  - pip install -r polysign/tests/requirements.txt

notifications:
  email: false

after_success:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL

after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL

script:
  - cd polysign/tests
  - pytest -v
